# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda"} # 2 hints
- ignore: {name: "Eta reduce"} # 2 hints
- ignore: {name: "Evaluate"} # 1 hint
- ignore: {name: "Fuse mapM_/map"} # 1 hint
- ignore: {name: "Redundant $"} # 2 hints
- ignore: {name: "Redundant bang pattern"} # 2 hints
- ignore: {name: "Redundant bracket"} # 9 hints
- ignore: {name: "Redundant where"} # 1 hint
- ignore: {name: "Unused LANGUAGE pragma"} # 5 hints
- ignore: {name: "Use <$>"} # 2 hints
- ignore: {name: "Use const"} # 4 hints
- ignore: {name: "Use infix"} # 1 hint
- ignore: {name: "Use lambda-case"} # 3 hints
- ignore: {name: "Use list comprehension"} # 1 hint
- ignore: {name: "Use uncurry"} # 1 hint
- ignore: {name: "Use zipWith"} # 1 hint