name: store
version: "0.7.15"
synopsis: Fast binary serialization
maintainer: Michael Sloan <mgsloan@gmail.com>
license: MIT
copyright: 2016 FP Complete
github: mgsloan/store
category: Serialization, Data
extra-source-files:
  - ChangeLog.md
  - README.md
tested-with:
  - GHC==9.0.1
  - GHC==8.10.4
  - GHC==8.8.4
  - GHC==8.6.5
  - GHC==8.4.4
  - GHC==8.2.2
  - GHC==8.0.2
  - GHC==7.10.3

flags:
  comparison-bench:
    default: false
    manual: true

  small-bench:
    default: false
    manual: true

  integer-simple:
    description: >-
      Use the [simple integer library](http://hackage.haskell.org/package/integer-simple)
      instead of [integer-gmp](http://hackage.haskell.org/package/integer-gmp)
    default: False
    manual: False

ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -O2

dependencies:
# Meaningful constraints.
  - base >=4.7 && <5

  # Core package tightly coupled to this package
  - store-core >=0.4 && <0.5

  # Utilities package tightly coupled to the TH code
  - th-utilities >=0.2

  # Due to removal of 'internal' from MonadPrim in 0.6
  - primitive >=0.6

  # Due to behavior change for reification errors
  - th-reify-many >=0.1.6

  # Lower bounds based on 7.8 config.
  - array >=0.5.0.0
  - base-orphans >=0.4.3
  - base64-bytestring >= 0.1.1
  - bytestring >=0.10.4.0
  - containers >=0.5.5.1
  - cryptohash >=0.11.6
  - deepseq >=1.3.0.2
  - directory >= 1.2
  - filepath >= 1.3
  - ghc-prim >=0.3.1.0
  - hashable >=1.2.3.1
  - hspec >=2.1.2
  - hspec-smallcheck >=0.3.0
  - lifted-base >=0.2.3.3
  - monad-control >=0.3.3.0
  - mono-traversable >=0.7.0
  - nats >=1
  - resourcet >=1.1.3.3
  - safe >=0.3.8
  - smallcheck >=1.1.1
  - syb >=0.4.4
  - template-haskell >=2.9.0.0
  - text >=1.2.0.4
  - th-lift >=0.7.1
  - th-lift-instances >=0.1.4
  - th-orphans >= 0.13.2
  - time >=1.5
  - transformers >=0.3.0.0
  - unordered-containers >=0.2.5.1
  - vector >=0.10.12.3 && <0.13
  - void >=0.5.11
  - free >=4.11
  - network >=2.6.0.2
  - async >=2.0.2
  - contravariant >=1.3
  - bifunctors >=4.0
when:
  # NOTE: The serialization of Integer is different when this flag is enabled.
  - condition: flag(integer-simple)
    then:
      dependencies: integer-simple >= 0.1.1.1
    else:
      dependencies: integer-gmp >= 0.5.1.0
      cpp-options: -DINTEGER_GMP
  - condition: impl(ghc < 8.0)
    dependencies:
      - fail >=4.9
      - semigroups >=0.8
library:
  source-dirs: src
  other-modules:
    - Data.Store.Impl

tests:
  store-test:
    source-dirs: test
    main: Spec.hs
    other-modules:
      - Data.Store.UntrustedSpec
      - Data.StoreSpec
      - Data.StoreSpec.TH
      - System.IO.ByteBufferSpec
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - store
      - clock >=0.3
    build-tools: hspec-discover:hspec-discover

benchmarks:
  store-bench:
    source-dirs: bench
    main: Bench.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N1 -with-rtsopts=-s -with-rtsopts=-qg
    dependencies:
      - criterion
      - store
    when:
      - condition: flag(comparison-bench)
        dependencies:
          - cereal
          - binary
          - vector-binary-instances
          - cereal-vector
        cpp-options: -DCOMPARISON_BENCH
      - condition: flag(small-bench)
        cpp-options: -DSMALL_BENCH
  store-weigh:
    source-dirs: test
    main: Allocations.hs
    other-modules: []
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-T -O2
    dependencies:
      - store
      - weigh
      - criterion
      - cereal
      - cereal-vector
      - vector-binary-instances
