name: store-core
version: "0.4.4.6"
synopsis: Fast and lightweight binary serialization
maintainer: Michael Sloan <mgsloan@gmail.com>
license: MIT
copyright: 2016 FP Complete
github: fpco/store
category: Serialization, Data
extra-source-files:
  - ChangeLog.md
tested-with:
  - GHC==9.4.5
  - GHC==9.2.8
  - GHC==9.0.2
  - GHC==8.10.7
  - GHC==8.8.4
  - GHC==8.6.5
  - GHC==8.4.4

flags:
  force-alignment:
    default: false
    manual: true

ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -O2

dependencies:
  - base >=4.7 && <5
  - primitive >=0.6 && < 1.0 # Due to removal of 'internal' from MonadPrim in 0.6
  - bytestring >=0.10.4.0 && < 1.0 # soft
  - transformers >=0.3.0.0 && < 1.0 # soft
  - ghc-prim >=0.3.1.0 && < 1.0 # soft
  - text >=1.2.0.4 && < 1.3 || >= 2.0 && < 2.2 #soft

library:
  source-dirs: src

when:
  - condition: flag(force-alignment) || arch(PPC) || arch(PPC64) || arch(Mips) || arch(Sparc) || arch(Arm)
    cpp-options: -DALIGNED_MEMORY
  - condition: impl(ghc < 8.0)
    dependencies: fail >=4.9 # shim for Control.Monad.Fail on older bases
