# store-streaming was forked from store-0.4.3.3

name: store-streaming
version: "0.2.0.3"
synopsis: Streaming interfaces for `store`
maintainer: Michael Sloan <mgsloan@gmail.com>
license: MIT
copyright: 2016 FP Complete
github: fpco/store
category: Serialization, Data
extra-source-files:
  - ChangeLog.md
tested-with:
  - GHC==9.4.5
  - GHC==9.2.8
  - GHC==9.0.2
  - GHC==8.10.7
  - GHC==8.8.4
  - GHC==8.6.5
  - GHC==8.4.4

ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -O2

dependencies:
  - async >=2.0.2
  - base >=4.7 && <5
  - bytestring >=0.10.4.0
  - conduit >=1.2.3.1
  - free >=4.11
  - resourcet >=1.1.3.3
  - store >=0.4.3.4
  - store-core >=0.4.1
  - streaming-commons >=0.1.10.0
  - text >=1.2.0.4
  - transformers >=0.3.0.0

when:
  - condition: impl(ghc < 8.0)
    dependencies: fail >=4.9

library:
  source-dirs: src

tests:
  store-test:
    source-dirs: test
    main: Spec.hs
    other-modules:
      - Data.Store.StreamingSpec
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-smallcheck
      - network
      - smallcheck
      - store
      - store-streaming
      - void
    build-tools: hspec-discover:hspec-discover
